spring.application.name=RecruiterFahrzeug

# PostgreSQL-Datenbankverbindung
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fahrzeug}
spring.datasource.username=${DB_USER:XOXOXyourName}
spring.datasource.password=${DB_PASSWORD:XOXOXchooseSafePasswords}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring JPA Konfiguration
spring.jpa.hibernate.ddl-auto=update

# SQL-Logs (Optional, for Debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.whitelabel.enabled=true